name = "HigherOrderFoodwebs"
uuid = "573a6084-d739-11ed-30ee-8d814a9e0f06"
version = "0.1.0"
authors = ["Jake Harvey <jacob.harvey@mail.mcgill.ca>"]

[deps]
AnnotatedHypergraphs = "121eab65-6eab-4c2f-bb7d-b6867ee8c3ea"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
NaNMath = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
SpeciesInteractionNetworks = "49e116ef-912f-4766-9e56-896a49944adc"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"

[sources]
AnnotatedHypergraphs = {rev = "main", url = "https://github.com/jkharv/AnnotatedHypergraphs.jl.git"}

[compat]
AnnotatedHypergraphs = "0.1.0"
Combinatorics = "1.0.3"
LinearAlgebra = "1.11.0"
MacroTools = "0.5.16"
NaNMath = "1.1.3"
OrdinaryDiffEqRosenbrock = "1.9.0"
OrdinaryDiffEqTsit5 = "1.1.0"
RuntimeGeneratedFunctions = "0.5.15"
SparseArrays = "1.11.0"
SpecialFunctions = "2.5.1"
SpeciesInteractionNetworks = "0.0.1"
