name = "HigherOrderFoodwebs"
uuid = "573a6084-d739-11ed-30ee-8d814a9e0f06"
authors = ["Jake Harvey <jacob.harvey@mail.mcgill.ca>"]
version = "0.1.0"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpeciesInteractionNetworks = "49e116ef-912f-4766-9e56-896a49944adc"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
